#use_frameworks!

platform :ios, '8.0'

target 'JXVideoAds_Example' do
  pod 'JXVideoAds', :path => '../'
  
  #  target 'JXVideoAds' do
  #    inherit! :search_paths
  #    pod 'GoogleAds-IMA-iOS-SDK'
  #
  #  end
  
end

